name: go test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.21']
    steps:
      - uses: actions/checkout@v3
      - name: set up go
        uses: actions/setup-go@v4
        with:
          go-version:  ${{ matrix.go-version }}

      - name: go download
        working-directory: ./emily
        run: go mod download

      - name: go build
        working-directory: ./emily
        run: go build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: go test
        working-directory: ./emily
        run: go test -coverprofile=coverage.out ./...

      - name: upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: ./emily/coverage.out

