name: go test

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        go-version: ["1.21"]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./emily
    steps:
      - uses: actions/checkout@v3
      - name: set up go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: go download
        run: go mod download

      - name: go build
        run: go build

      - name: go test
        run: go test -coverprofile=coverage.out ./...

      - name: upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.out
